Generate json files
nearform/osshealth pull request #68
Opened 2023-08-15 15:54 UTC by relvao

closes #7 

Pulls data from github and api scorecard and writes json files into the assets folder of the website.
Still needs work to adjust the schema to what is needed in the UI but will do that in a separate PR so this ins't too big

2023-08-16 14:14 UTC, Puppo requested changes

2023-08-16 14:35 UTC, relvao commented on build-scripts/src/github.ts
> +export default async function* queryGitHub(args: QueryGitHubArgs & GitHubClientArgs) {
I prefer to have implicit return types for no special reason than that I don't want to have to do any more work than absolutely necessary ;) 
I don't have a strong position though. I'll rewrite all fns to have explicit return types.

2023-08-16 14:50 UTC, relvao commented on build-scripts/src/index.ts
> +if (!fs.existsSync(options.path)) {
I'll move it into a fn and make the rest of the process wait on it to be resolved.

2023-08-17 07:46 UTC, Puppo submitted a review, later dismissed

2023-08-17 07:46 UTC, Puppo commented on build-scripts/src/index.ts
> +interface IndexData {
`IndexData` is a bit difficult to understand, in my opinion. Maybe something like `RepositoryInfoStatus`. I understood that it's the `index.json` content, but using a better name can help to understand what this file contains.

2023-08-17 07:46 UTC, Puppo commented on build-scripts/src/index.ts
> +  for await (const gitHubItem of queryGitHub(queryGitHubArgs)) {
This is a simple thought.
I don't know how many repositories we are and if there is a rate limit in these APIs, but using an asyncIterator, we call the API every iteration. I think this affects the execution time and the number of minutes for the GitHub Actions increases. Understanding if it's possible to resolve this issue using a `Promise.all` or a `Promise.allSettled` to "parallelise" all the requests and then manipulate the data after.
I don't want to refactor the codebase now; I just want to raise the flag on this point. This is impossible if we have a rate limit in the API, but maybe understanding this solution could be helpful. We can also go ahead with the current solution, check the time and the performance, and refactor the codebase in the future.

2023-08-17 08:34 UTC, merged